-- First Response / GovTOS Supabase schema
-- Run this in the Supabase SQL Editor once.

create extension if not exists pgcrypto;

create table if not exists public.complaints (
  id text primary key,
  created_at timestamptz not null default now(),
  category text not null,
  journey text not null check (journey in ('urgent','standard','safety')),
  status text not null default 'received' check (status in ('received','cyber_cell','outcome')),
  story text not null default '',
  amount text,
  platform text,
  updated_at timestamptz not null default now()
);

create index if not exists complaints_created_at_idx on public.complaints(created_at desc);
create index if not exists complaints_status_idx on public.complaints(status);

alter table public.complaints enable row level security;

create table if not exists public.complaint_status_events (
  id bigint generated by default as identity primary key,
  complaint_id text not null references public.complaints(id) on delete cascade,
  state text not null check (state in ('received','cyber_cell','outcome')),
  timestamp timestamptz not null default now(),
  plain_explanation text not null
);

create index if not exists complaint_status_events_case_idx
  on public.complaint_status_events(complaint_id, timestamp desc);

alter table public.complaint_status_events enable row level security;

create table if not exists public.evidence_items (
  id uuid primary key default gen_random_uuid(),
  complaint_id text references public.complaints(id) on delete cascade,
  label text not null,
  type text not null,
  file_path text,
  created_at timestamptz not null default now()
);

alter table public.evidence_items enable row level security;

-- Synthetic records for the hackathon demo. Safe, non-real data only.
insert into public.complaints (id, created_at, category, journey, status, story, amount, platform)
values
('FR-260814-4821','2026-08-14','Financial fraud','urgent','cyber_cell','UPI payment made after a fake bank call.','₹18,500','UPI'),
('FR-260816-1930','2026-08-16','Online harassment','standard','received','Repeated threatening messages from a social account.',null,'Instagram'),
('FR-260817-7712','2026-08-17','Impersonation','standard','cyber_cell','A profile copied the citizen name and photographs.',null,'Instagram'),
('FR-260820-4406','2026-08-20','Cyberbullying','standard','received','Repeated abusive messages in a group chat.',null,'WhatsApp'),
('FR-260821-9024','2026-08-21','Account takeover','standard','outcome','Social account access was lost after a phishing link.',null,'Social media'),
('FR-260823-3158','2026-08-23','Fake customer support','urgent','cyber_cell','Fake support agent requested remote access and payment.','₹7,200','Phone')
on conflict (id) do nothing;

-- The Next.js API talks to Supabase server-side with SUPABASE_SERVICE_ROLE_KEY.
-- Never expose that key through NEXT_PUBLIC_* variables.
-- Before a real public launch, add authentication, stricter RLS, retention rules,
-- audit logging and a server-side authorization model.