'use client';

import { useMemo, useState } from 'react';
import { aiDraft, aiScamReason, aiTriage } from '../ai/openaiClient';
import { extractIncidentDraft } from '../ai/extractIncidentDraft';
import { publicCaseSignals, type CaseSignal } from '../data/publicCaseSignals';
import { scamCheck } from '../scam-check/scamCheck';
import { buildStatusTimeline, calculateTypicalRange } from '../status/statusMachine';
import { classifyWithRules, overrideTriage, type TriageResult } from '../triage/triageRules';
import { checkIncidentCharacters } from '../validation/characterGuard';
import { syntheticHistoricalCases } from '../data/syntheticCases';
import type { Journey } from '../types/models';
import './winner.css';

type Stage = 'home' | 'urgent' | 'standard' | 'safety' | 'intelligence' | 'status' | 'submitted';
type Evidence = { id: string; label: string; type: string };

const demoStory = 'A caller pretended to be from my bank and I transferred ₹18,500.';

function Header({ onHome, onSafety, onIntelligence, onStatus }: { onHome: () => void; onSafety: () => void; onIntelligence: () => void; onStatus: () => void }) {
  return <header className="topbar"><button className="brand" onClick={onHome} aria-label="First Response home"><span className="brand-mark">FR</span><span><b>First Response</b><small>Cyber help, made understandable</small></span></button><nav aria-label="Primary"><button onClick={onSafety}>Online safety</button><button onClick={onIntelligence}>Check a signal</button><button onClick={onStatus}>Track</button><span className="lang-pill">हिंदी</span></nav></header>;
}

function AIHelper({ onRoute }: { onRoute: (j: Journey, reason: string) => void }) {
  const [open, setOpen] = useState(false); const [text, setText] = useState(''); const [answer, setAnswer] = useState(''); const [loading, setLoading] = useState(false);
  async function ask() { if (!text.trim()) return; setLoading(true); try { const r = await aiTriage(text); setAnswer(r.reason); onRoute(r.journey, r.reason); } catch { const r = classifyWithRules(text); setAnswer(`A good starting point is ${r.label}. You can always change this.`); onRoute(r.journey, r.label); } finally { setLoading(false); } }
  return <div className="ai-helper"><button className="ai-fab" onClick={() => setOpen(!open)} aria-expanded={open}>✦ <span>Ask AI</span></button>{open && <div className="ai-pop" role="dialog" aria-label="First Response AI"><div className="ai-pop-head"><span className="ai-spark">✦</span><div><b>First Response AI</b><small>Tell me what happened. I’ll help sort the next step.</small></div></div><textarea value={text} onChange={e => setText(e.target.value)} placeholder="For example: Someone is threatening me on Instagram…" />{answer && <div className="ai-answer">{answer}</div>}<button className="btn navy" onClick={ask} disabled={loading || !text.trim()}>{loading ? 'Understanding…' : 'Help me decide'}</button></div>}</div>;
}

function PathCard({ tone, icon, label, title, text, onClick }: { tone: string; icon: string; label: string; title: string; text: string; onClick: () => void }) {
  return <button className={`path-card ${tone}`} onClick={onClick}><span className="path-icon">{icon}</span><span className="path-copy"><small>{label}</small><b>{title}</b><span>{text}</span></span><strong className="path-arrow">→</strong></button>;
}

export default function Home() {
  const [stage, setStage] = useState<Stage>('home');
  const [story, setStory] = useState(''); const [showAIInput, setShowAIInput] = useState(false); const [triageReason, setTriageReason] = useState(''); const [triageLoading, setTriageLoading] = useState(false);
  const [triage, setTriage] = useState<TriageResult>(() => classifyWithRules(demoStory));
  const [description, setDescription] = useState(demoStory); const [amount, setAmount] = useState('₹18,500'); const [platform, setPlatform] = useState(''); const [approximateTime, setApproximateTime] = useState('');
  const [draft, setDraft] = useState(() => extractIncidentDraft(demoStory)); const [draftSummary, setDraftSummary] = useState(''); const [aiLoading, setAiLoading] = useState(false);
  const [scamInput, setScamInput] = useState(''); const [scamExplanation, setScamExplanation] = useState(''); const [approved, setApproved] = useState(false);
  const [safetyIssue, setSafetyIssue] = useState(''); const [intelligenceQuery, setIntelligenceQuery] = useState(''); const [selectedSignal, setSelectedSignal] = useState<CaseSignal | null>(null); const [complaints, setComplaints] = useState<any[]>([]); const [dbConnected, setDbConnected] = useState(false); const [dbLoading, setDbLoading] = useState(false); const [ack, setAck] = useState('');
  const [evidence, setEvidence] = useState<Evidence[]>([]);

  const characterGuard = useMemo(() => checkIncidentCharacters(description), [description]);
  const scam = useMemo(() => scamCheck(scamInput), [scamInput]);
  const statuses = useMemo(() => buildStatusTimeline(syntheticHistoricalCases, triage.incidentType, 6), [triage.incidentType]);
  const range = useMemo(() => calculateTypicalRange(syntheticHistoricalCases, triage.incidentType), [triage.incidentType]);
  const signals = useMemo(() => { const q = intelligenceQuery.trim().toLowerCase(); return q ? publicCaseSignals.filter(s => `${s.identifier} ${s.category} ${s.patterns.join(' ')}`.toLowerCase().includes(q)) : publicCaseSignals; }, [intelligenceQuery]);

  function route(journey: Journey, reason = '') { setTriage(overrideTriage(journey)); setTriageReason(reason); setDescription(story || demoStory); setStage(journey); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function chooseWithAI() { if (!story.trim()) return; setTriageLoading(true); try { const r = await aiTriage(story); route(r.journey, r.reason); } catch { const r = classifyWithRules(story); route(r.journey, `Rule fallback: ${r.label}`); } finally { setTriageLoading(false); } }
  async function generateDraft() { setAiLoading(true); try { const r = await aiDraft({ story: description, amount, approximateTime, platform }); setDraft(r); setDraftSummary(r.summary); } catch { setDraft(extractIncidentDraft(description)); setDraftSummary('The local extraction is ready; live AI drafting needs the server API key.'); } finally { setAiLoading(false); } }
  async function explainScam() { if (!scamInput.trim()) return; try { const signal = scam.signature ? `${scam.signature.kind}: ${scam.signature.label}` : 'No signature matched'; const r = await aiScamReason({ query: scamInput, result: scam.result, signal }); setScamExplanation(r.explanation); } catch { setScamExplanation('The deterministic scan is the authoritative result.'); } }
  async function submitReport() { const id = `FR-${new Date().toISOString().slice(2,10).replaceAll('-', '')}-${Math.floor(1000 + Math.random() * 9000)}`; const category = safetyIssue || (triage.incidentType === 'financial_fraud' ? 'Financial fraud' : 'Cybercrime report'); try { const r = await fetch('/api/complaints', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, journey: triage.journey, category, story: description, amount, platform }) }); const data = await r.json(); setDbConnected(Boolean(data.connected)); } catch {} setAck(id); setStage('submitted'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function loadComplaints() { setDbLoading(true); try { const r = await fetch('/api/complaints'); const data = await r.json(); setComplaints(data.complaints || []); setDbConnected(Boolean(data.connected)); } finally { setDbLoading(false); } }

  return <main className="app-shell"><div className="page-frame"><Header onHome={() => setStage('home')} onSafety={() => setStage('safety')} onIntelligence={() => setStage('intelligence')} onStatus={() => { setStage('status'); loadComplaints(); }} />
    {stage === 'home' && <>
      <section className="hero-new"><div className="hero-copy-new"><p className="eyebrow">CITIZEN CYBER RESPONSE</p><h1>Something happened online?<br/><em>Start here.</em></h1><p className="hero-lede">Tell us what happened in your own words. First Response helps you understand the risk, preserve evidence and choose the right next step.</p><div className="hero-input"><span>✦</span><input value={story} onChange={e => setStory(e.target.value)} placeholder="“Someone is threatening me on Instagram…”" onKeyDown={e => { if (e.key === 'Enter') chooseWithAI(); }} /><button onClick={chooseWithAI} disabled={triageLoading || !story.trim()}>{triageLoading ? '…' : '→'}</button></div><div className="hero-meta"><span>AI-guided</span><i/> <span>Evidence-first</span><i/> <span>Human-readable</span></div></div><div className="hero-character"><div className="character-glow"/><div className="character-figure" aria-label="First Response cyber safety officer illustration"><div className="char-head"><span className="char-hair"/><span className="char-eye e1"/><span className="char-eye e2"/><span className="char-smile"/></div><div className="char-cap">✦</div><div className="char-body"><span className="char-badge">CYBER</span><span className="char-pocket p1"/><span className="char-pocket p2"/></div></div><div className="speech">I’ll help you<br/><b>take the right next step.</b></div></div></section>
      <section className="path-section"><div className="section-head"><div><p className="eyebrow">CHOOSE A STARTING POINT</p><h2>What do you need right now?</h2></div><span>01 — 04</span></div><div className="path-grid"><PathCard tone="urgent" icon="!" label="URGENT · FINANCIAL FRAUD" title="Money is moving right now" text="Act first. Get the 1930 route and prepare the essentials." onClick={() => route('urgent')} /><PathCard tone="safe" icon="◎" label="ONLINE SAFETY" title="I’m being bullied or threatened" text="Build an evidence-first safety plan for harassment, threats or blackmail." onClick={() => setStage('safety')} /><PathCard tone="report" icon="＋" label="REPORT" title="I need to report something" text="Cyberbullying, impersonation, account takeover, scams and more." onClick={() => route('standard')} /><PathCard tone="track" icon="↗" label="TRACK" title="I already filed a complaint" text="Find your reference and understand what happens next." onClick={() => { setStage('status'); loadComplaints(); }} /></div></section>
      <section className="intel-teaser"><div><p className="eyebrow">CYBERCRIME INTELLIGENCE</p><h2>Check a phone, UPI ID, URL or social handle.</h2><p>Search available risk signals before you trust it. A clean result is never a guarantee of safety.</p></div><button className="btn navy" onClick={() => setStage('intelligence')}>Check a signal →</button></section>
      <section className="how-section"><div className="section-head"><div><p className="eyebrow">HOW IT WORKS</p><h2>From confusion to a clear trail.</h2></div></div><div className="how-grid"><article><b>01</b><h3>Understand</h3><p>AI turns a messy story into a plain-language incident summary and explains why a route was chosen.</p></article><article><b>02</b><h3>Preserve</h3><p>Evidence Vault keeps screenshots, identifiers, URLs and a simple incident timeline together.</p></article><article><b>03</b><h3>Act</h3><p>Urgent financial cases surface 1930 first; other cases move into a calmer reporting flow.</p></article><article><b>04</b><h3>Track</h3><p>A case reference and timeline make the next step visible instead of leaving you guessing.</p></article></div></section>
      <section className="voice-banner"><div><p className="eyebrow">MADE FOR REAL PEOPLE</p><h2>Type it. Speak it. Even in Hindi.</h2><p>The interface is designed around plain language, large controls and voice-friendly conversations.</p></div><button className="btn light" onClick={() => setShowAIInput(true)}>{showAIInput ? 'AI helper ready' : 'Try AI helper ✦'}</button></section>
      <footer className="site-footer-new"><div><b>FIRST RESPONSE</b><p>Cyber help that explains what to do next.</p></div><div><small>QUICK ACCESS</small><button onClick={() => setStage('safety')}>Online safety</button><button onClick={() => setStage('intelligence')}>Check a signal</button><button onClick={() => { setStage('status'); loadComplaints(); }}>Track a complaint</button></div><div><small>OFFICIAL ROUTES</small><a href="https://www.cybercrime.gov.in/" target="_blank" rel="noreferrer">National Cyber Crime Reporting Portal ↗</a><a href="tel:1930">Financial cyber fraud: 1930</a></div><div className="footer-bottom"><span>Independent citizen-service interface</span><span>Use official government channels for actual filing</span></div></footer>
    </>}

    {stage === 'urgent' && <section className="journey"><div className="journey-hero urgent"><p className="eyebrow">URGENT FINANCIAL FRAUD</p><h1>Act first. Report second.</h1><p>If money is moving or has just moved, speed matters.</p><a className="call1930" href="tel:1930"><span>1930</span><b>Call the national cyber fraud helpline</b><small>Open your phone dialer</small></a><div className="step-row"><span>1 Call 1930</span><span>2 Contact your bank</span><span>3 Preserve evidence</span></div></div><div className="content-card"><div className="card-heading"><span>AI CASE BUILDER</span><b>Prepare the essentials</b></div><textarea className="textarea-main" value={description} onChange={e => setDescription(e.target.value)} placeholder="What happened?"/><div className="two-col"><input className="field" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Amount / loss"/><input className="field" value={platform} onChange={e => setPlatform(e.target.value)} placeholder="Bank / payment platform"/></div><input className="field" value={approximateTime} onChange={e => setApproximateTime(e.target.value)} placeholder="Approximate time"/><button className="btn teal" onClick={generateDraft} disabled={aiLoading}>{aiLoading ? 'Drafting…' : 'Structure my complaint with AI'}</button>{draftSummary && <div className="result-note">{draftSummary}</div>}<div className="draft-grid"><span>Loss <b>{draft.amount}</b></span><span>Type <b>{draft.approximateIncidentType}</b></span><span>Evidence <b>{draft.possibleEvidence.length} signals</b></span></div></div><EvidenceVault evidence={evidence} setEvidence={setEvidence}/><button className="btn navy big" onClick={submitReport}>Create case & continue →</button><button className="back-link" onClick={() => setStage('home')}>← Back</button></section>}

    {stage === 'standard' && <section className="journey"><div className="journey-heading"><p className="eyebrow">REPORT A CYBERCRIME</p><h1>Tell the story first.</h1><p>Cyberbullying, threats, impersonation, account takeover, scams and other online harm.</p></div><div className="category-pills">{['Cyberbullying','Online threat','Impersonation','Blackmail','Account takeover'].map(x => <button key={x} onClick={() => setSafetyIssue(x)}>{x}</button>)}</div><div className="content-card"><div className="card-heading"><span>01 · INCIDENT</span><b>{safetyIssue || 'Describe what happened'}</b></div><textarea className="textarea-main" value={description} onChange={e => setDescription(e.target.value)} placeholder="Tell us in your own words…"/>{characterGuard.blocked && <div className="warning"><b>Character warning:</b> {characterGuard.message}</div>}<div className="two-col"><input className="field" value={platform} onChange={e => setPlatform(e.target.value)} placeholder="Platform (Instagram, WhatsApp, UPI…)"/><input className="field" value={approximateTime} onChange={e => setApproximateTime(e.target.value)} placeholder="When did it happen?"/></div></div><div className="content-card"><div className="card-heading"><span>02 · SCAN</span><b>Check suspicious content</b></div><p className="muted">Paste a full message, long URL, UPI ID, phone number, email or social handle. The scan can find a signal inside long text.</p><textarea className="scan-box" value={scamInput} onChange={e => { setScamInput(e.target.value); setScamExplanation(''); }} placeholder="Paste suspicious content here…"/>{scamInput && <div className={`scan-result ${scam.result === 'MATCH' ? 'match' : scam.result === 'INCONCLUSIVE' ? 'inconclusive' : 'not-found'}`}><b>{scam.result}</b><p>{scam.message}</p></div>}<button className="btn navy" onClick={explainScam} disabled={!scamInput.trim()}>Explain the signal with AI</button>{scamExplanation && <div className="result-note">{scamExplanation}</div>}</div><EvidenceVault evidence={evidence} setEvidence={setEvidence}/><label className="check-row"><input type="checkbox" checked={approved} onChange={e => setApproved(e.target.checked)}/><span>I reviewed the details and evidence I want to submit.</span></label><button className="btn teal big" disabled={!approved} onClick={submitReport}>Prepare my complaint →</button><button className="back-link" onClick={() => setStage('home')}>← Back</button></section>}

    {stage === 'safety' && <section className="journey"><div className="journey-hero safety"><p className="eyebrow">ONLINE SAFETY MODE</p><h1>You don't have to figure this out alone.</h1><p>For bullying, threats, stalking, blackmail, impersonation or unwanted sharing.</p></div><div className="content-card"><div className="card-heading"><span>WHAT'S HAPPENING?</span><b>Choose the closest fit</b></div><div className="issue-grid">{['Cyberbullying','Repeated harassment','Threats','Blackmail','Impersonation','Intimate-image abuse'].map(x => <button key={x} className={safetyIssue === x ? 'selected' : ''} onClick={() => setSafetyIssue(x)}>{x}</button>)}</div>{safetyIssue && <div className="safety-plan"><p className="eyebrow">YOUR FIRST STEPS</p><h3>{safetyIssue}</h3><div><b>01</b><span>Preserve messages, profile URLs and timestamps before blocking or deleting anything.</span></div><div><b>02</b><span>Save original screenshots and keep the conversation in context.</span></div><div><b>03</b><span>If there is an immediate threat to your physical safety, contact local emergency services.</span></div><div><b>04</b><span>When ready, First Response can structure the cybercrime report.</span></div></div>}</div><div className="content-card evidence-callout"><div><p className="eyebrow">EVIDENCE FIRST</p><h2>Build a clean trail before you report.</h2><p className="muted">A simple timeline can be more useful than a folder full of disconnected screenshots.</p></div><button className="btn navy" onClick={() => setStage('standard')}>Build my report →</button></div><button className="back-link" onClick={() => setStage('home')}>← Back</button></section>}

    {stage === 'intelligence' && <section className="journey"><div className="journey-heading"><p className="eyebrow">CYBERCRIME INTELLIGENCE</p><h1>Check before you trust.</h1><p>Search a phone number, UPI ID, URL, email or social handle against available risk signals.</p></div><div className="intelligence-search"><span>⌕</span><input value={intelligenceQuery} onChange={e => { setIntelligenceQuery(e.target.value); setSelectedSignal(null); }} placeholder="Paste an identifier or search term…"/><button onClick={() => setIntelligenceQuery(intelligenceQuery.trim())}>Search</button></div><p className="source-note">Signals shown here are labeled by source. A clean result never means safe.</p><div className="signal-list">{signals.map(s => <button key={s.id} className="signal-row" onClick={() => setSelectedSignal(s)}><span className={`signal-kind ${s.kind}`}>{s.kind}</span><div><b>{s.identifier}</b><small>{s.category} · {s.reports} reports in the available dataset</small></div><strong>→</strong></button>)}{!signals.length && <div className="empty-state"><b>No matching signal found.</b><p>This dataset has no match. It does not certify the identifier as safe.</p></div>}</div>{selectedSignal && <div className="signal-detail"><button className="close-detail" onClick={() => setSelectedSignal(null)}>×</button><p className="eyebrow">RISK SIGNAL</p><h2>{selectedSignal.identifier}</h2><div className="risk-stat"><b>{selectedSignal.reports}</b><span>available reports</span></div><p><b>Pattern:</b> {selectedSignal.category}</p><div className="pattern-list">{selectedSignal.patterns.map(p => <span key={p}>{p}</span>)}</div><small>Source: {selectedSignal.source} · Last reported {selectedSignal.lastReported}</small><button className="btn red" onClick={() => { setScamInput(selectedSignal.identifier); setStage('standard'); }}>Use in my report →</button></div>}<button className="back-link" onClick={() => setStage('home')}>← Back</button></section>}

    {stage === 'status' && <section className="journey"><div className="journey-heading"><p className="eyebrow">CASE TRACKER</p><h1>Know what happens next.</h1><p>Search your First Response reference to see the current case trail.</p></div><div className="intelligence-search"><span>⌕</span><input placeholder="FR-260814-4821" onChange={e => setIntelligenceQuery(e.target.value)} /><button onClick={loadComplaints}>{dbLoading ? '…' : 'Find'}</button></div><div className="connection-pill">{dbConnected ? '● Connected to complaint database' : '● Demo records available · connect Supabase for shared storage'}</div>{complaints.length > 0 ? complaints.map(c => <div key={c.id} className="case-row"><div><span className="reference">{c.id}</span><b>{c.category}</b><p>{c.story}</p></div><span className={`status-dot ${c.status}`}>{c.status === 'received' ? 'Received' : c.status === 'cyber_cell' ? 'With cyber cell' : 'Outcome shared'}</span></div>) : <button className="sample-case" onClick={loadComplaints}>Load available case records</button>}<div className="timeline"><div className="timeline-head"><span>CASE JOURNEY</span><b>Typical {range.min}–{range.max} days</b></div>{statuses.map((s, i) => <div className="timeline-item" key={s.state}><span className={`timeline-node ${i === 0 ? 'active' : ''}`}>{i + 1}</span><div><b>{s.title}</b><p>{s.meaning}</p><small>Next: {s.next}</small></div></div>)}</div><button className="back-link" onClick={() => setStage('home')}>← Back</button></section>}

    {stage === 'submitted' && <section className="submitted"><div className="success-mark">✓</div><p className="eyebrow">CASE PREPARED</p><h1>Your trail is ready.</h1><p>The information you entered has been structured into a case record.</p><div className="case-reference"><small>REFERENCE</small><b>{ack}</b><span>Keep this number for your records.</span></div><div className="next-actions"><div><b>01</b><span>Preserve the original evidence.</span></div><div><b>02</b><span>For financial fraud, call 1930 immediately.</span></div><div><b>03</b><span>Use the official National Cyber Crime Reporting Portal for actual government filing.</span></div></div><a className="btn navy big" href="https://www.cybercrime.gov.in/" target="_blank" rel="noreferrer">Continue to official reporting →</a><button className="back-link" onClick={() => setStage('home')}>Return to First Response</button></section>}

    {showAIInput && stage === 'home' && <div className="ai-inline"><b>First Response AI</b><p>Describe anything you're unsure about and I’ll help route it.</p><textarea value={story} onChange={e => setStory(e.target.value)} placeholder="What happened?"/><button className="btn navy" onClick={chooseWithAI}>Continue →</button></div>}
    <AIHelper onRoute={route}/>
  </div></main>;
}

function EvidenceVault({ evidence, setEvidence }: { evidence: Evidence[]; setEvidence: (v: Evidence[]) => void }) {
  function add(label: string, type: string) { setEvidence([...evidence, { id: `${Date.now()}-${type}`, label, type }]); }
  return <div className="content-card evidence-vault"><div className="card-heading"><span>EVIDENCE VAULT</span><b>Keep the useful pieces together</b></div><div className="evidence-grid">{[['Screenshot','chat'],['Phone / UPI','upi'],['URL / profile','url'],['Notes','notes']].map(([label,type]) => <button key={type} onClick={() => add(label, type)}><span>＋</span><b>{label}</b><small>Add item</small></button>)}</div>{evidence.length > 0 && <div className="evidence-items">{evidence.map(e => <span key={e.id}>✓ {e.label}</span>)}</div>}<div className="evidence-tip"><b>Timeline tip</b><span>Keep the first message, important timestamps and the identifier visible in every screenshot.</span></div></div>;
}
